console.log("Hello Winc Academy");
let naam = "mirjam";
console.log(naam);
console.log(4+4);
console.log("4" + "4");
console.log(4 * 4);
console.log(4/4);
console.log(4 - 4);
console.log( 100 % 9);
let leeftijd = 49;
console.log(typeof(leeftijd));
let str_leeftijd = String(leeftijd);
console.log(typeof(str_leeftijd));